[workspace]
channels = ["conda-forge"]
name = "kt-exp-graph"
platforms = ["linux-64"]

[pypi-options]
index-url = "https://pypi.org/simple"

[dependencies]
python = "3.10.*"
optuna = ">=4.6.0,<5"
scikit-learn = ">=1.7.2,<2"
pandas = ">=2.3.3,<3"
pyarrow = ">=12.0.1,<13"
python-dotenv = ">=1.2.1,<2"
ruff = ">=0.15,<0.16"
pytest = ">=9.0.2,<10"

[pypi-dependencies]
dhg = "==0.9.*"
swanlab = "<0.8"
torch-geometric = ">=2.7.0, <3"

[feature.gpu.system-requirements]
cuda = "11.7"
[feature.gpu.dependencies]
cuda-version = "11.7.*"
[feature.gpu.pypi-dependencies]
torch = "==1.13.1+cu117"
pyg_lib = ">=0.4.0,<0.5"
[feature.gpu.pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu117"]
find-links = [{ url = "https://data.pyg.org/whl/torch-1.13.1+cu117.html" }]

[feature.cpu.pypi-dependencies]
torch = "==1.13.1"
pyg_lib = ">=0.4.0,<0.5"
[feature.cpu.pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cpu"]
find-links = [{ url = "https://data.pyg.org/whl/torch-1.13.1+cpu.html" }]

[environments]
cpu = { features = ["cpu"] }
default = { features = ["gpu"] }

[tasks]
lint = "ruff check ."
fmt = "ruff format ."
ckf = [{ task = "lint" }, { task = "fmt" }]
clean-cache = "find . -name '__pycache__' -type d -print0 | xargs -0 rm -rf && find . -name '*.py[co]' -delete && rm -rf runs/* swanlog/*"
